-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgcWQ6gSBNddSCdz0Q
BJkveSosZp6WtLOiP5CkirNwF4igCgYIKoZIzj0DAQehRANCAARtof0RfGX2FkLl
A9jeXMwAxWqzVkbO7s1Od9MJFvPSzlmJT/JE1H7BGZUH8eheFzTlm2+ifC0yivSA
ZuJpw8+X
-----END PRIVATE KEY-----